// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.mattermost.use-default-theme",
    "name": "Use Default Theme",
    "description": "Apply a custom theme to all users when they create their account.",
    "homepage_url": "https://github.com/phederal/mattermost-plugin-use-theme",
    "support_url": "https://github.com/phederal/mattermost-plugin-use-theme/issues",
    "release_notes_url": "https://github.com/phederal/mattermost-plugin-use-themereleases/tag/v0.5.0",
    "icon_path": "assets/starter-template-icon.svg",
    "version": "0.5.0+cb8594e",
    "min_server_version": "6.2.1",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "UseCustomTheme",
                "display_name": "Use Default Theme",
                "type": "longtext",
                "help_text": "Use Custom Theme JSON",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
